01 Numpy
===
NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array. It is the foundational library where SciPy (Scientific Python) library is built.

## Operations using NumPy
Using NumPy, a developer can perform the following operations −

* __Mathematical and logical operations on arrays.__

* Fourier transforms and routines for shape manipulation.

* Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

---

Ndarray Object
---
The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

In [1]:
import numpy as np 
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [2]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


## Python Lists vs. Numpy Arrays - What is the difference?

Numpy is the core library for scientific computing in Python. **It provides a high-performance multidimensional array object, and tools for working with these arrays.** 

The Python core library provided Lists. A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

A common beginner question is what is the real difference here. The answer is performance. Numpy data structures perform better in:

* **Size** - Numpy data structures take up less space
* **Performance** - they have a need for speed and are faster than lists
* **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built in.

---

## By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. eg. "ABCD"
- integer - used to represent integer numbers. eg. -1, -2, -3
- float - used to represent real numbers. eg. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent a number in complex plain. eg. 1.0 + 2.0j, 1.5 + 2.5j

Data Types
---
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [3]:
#The NumPy array object has a property called dtype that returns the data type of the array:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [4]:
# We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [5]:
# Converting Data Type on Existing Arrays

import numpy as np

arr = np.array([1.1, 2.1, 3.1])
print(arr)
print(arr.dtype)

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32


Array Attributes
---
Various array attributes of Numpy array

In [6]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print(a) 

[[1 2]
 [3 4]
 [5 6]]


In [8]:
#NumPy also provides a reshape function to resize an array.

import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
#ndarray.ndim This array attribute returns the number of array dimensions.

# let's first create our sample array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) # what does this function do?
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [10]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
a.ndim

1

In [11]:
# now reshape it 
b = a.reshape(2,4,3) 
print(b) 
# b is having three dimensions
print("we now have ",b.ndim," dimenions!")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
we now have  3  dimenions!


Array Creation Routines
---
A new ndarray object can be constructed by any of the following array creation routines

In [12]:
#numpy.empty
#It creates an uninitialized array of specified shape and dtype. It uses the following constructor −

import numpy as np 
x = np.empty([3,2], dtype = int) 
print (x)

#Note − The elements in an array show random values as they are not initialized.

[[1 2]
 [3 4]
 [5 6]]


In [13]:
#numpy.zeros
#Returns a new array of specified size, filled with zeros.

# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print(x)

[0. 0. 0. 0. 0.]


In [14]:
import numpy as np 
x = np.zeros((2,2))  
print(x)

[[0. 0.]
 [0. 0.]]


In [15]:
#numpy.ones
#Returns a new array of specified size and type, filled with ones.

import numpy as np 
x = np.ones([2,2], dtype = int) 
print(x)

[[1 1]
 [1 1]]


In [16]:
#numpy.asarray
#This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print(a)

[1 2 3]


In [17]:
# dtype is set 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
print(a)

[1. 2. 3.]


In [18]:
#numpy.arange
#This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −

import numpy as np 
x = np.arange(5) 
print(x)

[0 1 2 3 4]


In [19]:
import numpy as np 
# dtype set 
x = np.arange(5, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [20]:
# start and stop parameters set 
import numpy as np 
x = np.arange(10,20,2) 
print(x)

[10 12 14 16 18]


Indexing & Slicing
---
Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects ie. list

In [21]:
import numpy as np 
a = np.arange(10) 
print(a)

s = slice(2,7,2) 
print(a[s])

b = a[2:7:2] 
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 4 6]


In [22]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
print(b)

5


In [23]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print(a[2:])

[2 3 4 5 6 7 8 9]


In [24]:
# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print(a[2:5])

[2 3 4]


In [25]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)

# slice items starting from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [26]:
# Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
print(a) 
print('\n')  

# this returns array of items in the second column 
print('The items in the second column are:')  
print(a[...,1]) 
print('\n')  

# Now we will slice all items from the second row 
print('The items in the second row are:') 
print(a[1,...]) 
print('\n')  

# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:') 
print(a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


Iterating Over Array
---
NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

In [27]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Original array is:')
print(a)
print('\n')

print('Modified array is:')
for x in np.nditer(a):
    print(x)

#using normal python iteration
print("")
for x in a:
    for y in x:
        print(y)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55

0
5
10
15
20
25
30
35
40
45
50
55


## Other Array manipulations

In [28]:
#transpose

import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print("original:\n",a)
print()
print("transposed:\n",a.T)

original:
 [[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

transposed:
 [[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [29]:
#concatenate
import numpy as np
a = np.arange(0,10,5)
b = np.arange(10,20,5)

print(a)
print(b)

print(np.concatenate([a,b]))

[0 5]
[10 15]
[ 0  5 10 15]


In [30]:
#unique
import numpy as np 
a = np.array([5,2,6,2,7,5,6,8,2,9]) 

print('First array:') 
print(a) 
print('\n')  

print('Unique values of first array:') 
u = np.unique(a) 
print(u) 
print('\n')  


First array:
[5 2 6 2 7 5 6 8 2 9]


Unique values of first array:
[2 5 6 7 8 9]




# Numpy Operations: Examples

In [31]:
# string concatenation.

import numpy as np 
print('Concatenate two strings:')
print(np.char.add(['hello'],[' xyz']))
print('\n')

print('Concatenation example:')
print(np.char.add(['hello', 'hi'],[' abc', ' xyz']))

Concatenate two strings:
['hello xyz']


Concatenation example:
['hello abc' 'hi xyz']


In [32]:
# mathematical functions
import numpy as np 
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print('Original array:') 
print(a) 
print('\n')  

print('After rounding:') 
print(np.around(a))
print(np.around(a, decimals = 1))
print(np.around(a, decimals = -1))

Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [33]:
# arithmetic operations

import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('First array:') 
print(a) 
print('\n')  

print('Second array:') 
b = np.array([10,10,10]) 
print(b)
print('\n')  

print('Add the two arrays:') 
print(np.add(a,b) )
print('\n')  

print('Subtract the two arrays:') 
print(np.subtract(a,b) )
print('\n')  

print('Multiply the two arrays:') 
print(np.multiply(a,b)) 
print('\n')  

print('Divide the two arrays:') 
print(np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [34]:
#statistical operations

import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:')
print(a) 
print('\n')  

print('Applying mean() function:') 
print(np.mean(a)) 
print('\n')  

print('Applying mean() function along axis 0:') 
print(np.mean(a, axis = 0)) 
print('\n')  

print('Applying mean() function along axis 1:')
print(np.mean(a, axis = 1))

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying mean() function:
3.6666666666666665


Applying mean() function along axis 0:
[2.66666667 3.66666667 4.66666667]


Applying mean() function along axis 1:
[2. 4. 5.]


- - -
**NEXT TOPIC:**  [Pandas](02_pandas.ipynb)